# Generated by Django 5.1.2 on 2024-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField(unique=True)),
                ("warmth", models.IntegerField(default=50)),
                ("brightness", models.IntegerField(default=50)),
                ("contrast", models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name="RecordingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_recording", models.BooleanField(default=False)),
                ("recorded_time", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
