# Generated by Django 5.1.2 on 2024-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_app", "0002_recordingstatus_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingstatus",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
