# Generated by Django 5.1.2 on 2024-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_app", "0004_recordingstatus_device_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recordingstatus",
            old_name="last_updated",
            new_name="last_recording_time",
        ),
        migrations.AlterField(
            model_name="recordingstatus",
            name="device_id",
            field=models.IntegerField(unique=True),
        ),
    ]
