# Generated by Django 5.1.2 on 2024-11-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "server_app",
            "0005_rename_last_updated_recordingstatus_last_recording_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("total_duration", models.IntegerField()),
                ("estimated_end_time", models.DateTimeField()),
                ("status", models.CharField(default="recording", max_length=20)),
            ],
        ),
    ]
