# Generated by Django 5.1.2 on 2024-11-14 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server_app", "0007_recording_delete_recordingsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordingstatus",
            name="last_recording_time",
        ),
        migrations.RemoveField(
            model_name="recordingstatus",
            name="recorded_time",
        ),
        migrations.RemoveField(
            model_name="recordingstatus",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="recordingstatus",
            name="status_code",
        ),
    ]
